
boxbot:
  # Publish all joint states----------------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position controllers -------------------------------------------
  left_shoulder_1_joint_controller:
    type: position_controllers/JointPositionController
    joint: left_shoulder_1_joint

  left_shoulder_2_joint_controller:
    type: position_controllers/JointPositionController
    joint: left_shoulder_2_joint

  left_elbow_joint_controller:
    type: position_controllers/JointPositionController
    joint: left_elbow_joint

  left_wrist_1_joint_controller:
    type: position_controllers/JointPositionController
    joint: left_wrist_1_joint

  left_wrist_2_joint_controller:
    type: position_controllers/JointPositionController
    joint: left_wrist_2_joint

  left_gripper_joint_controller:
    type: position_controllers/JointPositionController
    joint: left_gripper_joint

  left_gripper_mimic_joint_controller:
    type: position_controllers/JointPositionController
    joint: left_gripper_prismatic_joint_2

  right_shoulder_1_joint_controller:
    type: position_controllers/JointPositionController
    joint: right_shoulder_1_joint

  right_shoulder_2_joint_controller:
    type: position_controllers/JointPositionController
    joint: right_shoulder_2_joint

  right_elbow_joint_controller:
    type: position_controllers/JointPositionController
    joint: right_elbow_joint

  right_wrist_1_joint_controller:
    type: position_controllers/JointPositionController
    joint: right_wrist_1_joint

  right_wrist_2_joint_controller:
    type: position_controllers/JointPositionController
    joint: right_wrist_2_joint

  right_gripper_joint_controller:
    type: position_controllers/JointPositionController
    joint: right_gripper_joint

  right_gripper_mimic_joint_controller:
    type: position_controllers/JointPositionController
    joint: right_gripper_prismatic_joint_2

  gazebo_ros_control/pid_gains:
    left_shoulder_1_joint: {p: 50.0, i: 0.1, d: 1.0}
    left_shoulder_2_joint: {p: 50.0, i: 0.1, d: 1.0}
    left_elbow_joint: {p: 50.0, i: 0.1, d: 1.0}
    left_wrist_1_joint: {p: 50.0, i: 0.1, d: 1.0}
    left_wrist_2_joint: {p: 50.0, i: 0.1, d: 1.0}
    left_gripper_joint: {p: 50.0, i: 0.1, d: 1.0}
    left_gripper_prismatic_joint_2: {p: 50.0, i: 0.1, d: 1.0}
    right_shoulder_1_joint: {p: 50.0, i: 0.1, d: 1.0}
    right_shoulder_2_joint: {p: 50.0, i: 0.1, d: 1.0}
    right_elbow_joint: {p: 50.0, i: 0.1, d: 1.0}
    right_wrist_1_joint: {p: 50.0, i: 0.1, d: 1.0}
    right_wrist_2_joint: {p: 50.0, i: 0.1, d: 1.0}
    right_gripper_joint: {p: 50.0, i: 0.1, d: 1.0}
    right_gripper_prismatic_joint_2: {p: 50.0, i: 0.1, d: 1.0}
