# Kinematic parameters for the 6-DOF arm boxbot.

base_link: arm_base_link
eef_link: wrist_2_link

joint_names: [shoulder_1_joint, shoulder_2_joint, elbow_joint, wrist_1_joint, wrist_2_joint, gripper_joint]

joints: {
    shoulder_1_joint: {id: 1, ticks: 4096, range: 360.0, max_speed: 100.0},
    shoulder_2_joint: {id: 2, ticks: 4096, range: 360.0, min_angle: -90.0, max_angle: 90, max_speed: 100.0},
    elbow_joint: {id: 3, ticks: 4096, range: 360.0, max_speed: 100.0, invert: true},
    wrist_1_joint: {id: 4, ticks: 4096, range: 360.0, max_speed: 100.0},
    wrist_2_joint: {id: 5, ticks: 1024, range: 300.0, min_angle: -150.0, max_angle: 150.0, max_speed: 100.0},
    gripper_joint: {id: 6, max_angle: 0, min_angle: -145, max_speed: 90, type: prismatic, radius: 0.0078, connector: 0.024, offset: 0.016},
}

DH: [[0.0, 0.0, 0.0, 0.0],
     [pi/2, 0.0, 0.0, -1.24282],
     [0.0, 0.15, 0.0, -0.32798],
     [pi, 0.14203, 0.0, 0.0],
     [-pi/2, 0.0, 0.0715, 0.0]]

planning_group: "_arm"
gripper_group: "_gripper"

left_arm_base_pose: [0.0, 0.099613, 0.24953, -0.707107, 0.0, 0.0, 0.707107]
right_arm_base_pose: [0.0, -0.099613, 0.24953, 0.707107, 0.0, 0.0, 0.707107]
