# Setup for full kinematic model

model_config: {
    description: boxbot_description/robots/boxbot_6dof.urdf,
    subsystems: {
        left_arm: {
            name: left_arm,
            base_link: left_arm_base_link,
            tool_link: left_gripper_rail_link,
            joint_names: [left_shoulder_1_joint, left_shoulder_2_joint, left_elbow_joint, left_wrist_1_joint, left_wrist_2_joint, left_wrist_3_joint],
            eef: {
                name: left_arm_gripper,
                type: single_servo_parallel_gripper,
                base_link: left_gripper_rail_link,
                joint_names: [left_gripper_joint],
                limits: [0.0, 0.09],
                equation: {
                    type: linear,
                    a: -8.216656807,
                    b: 0.016433314,
                }
            }
        },
        right_arm: {
            name: right_arm,
            base_link: right_arm_base_link,
            tool_link: right_gripper_rail_link,
            joint_names: [right_shoulder_1_joint, right_shoulder_2_joint, right_elbow_joint, right_wrist_1_joint, right_wrist_2_joint, right_wrist_3_joint],
            eef: {
                name: right_arm_gripper,
                type: single_servo_parallel_gripper,
                base_link: right_gripper_rail_link,
                joint_names: [right_gripper_joint],
                limits: [0.0, 0.09],
                equation: {
                    type: linear,
                    a: -8.216656807,
                    b: 0.016433314,
                }
            }
        },
        #head: {
            #name: head,
            #base_link: torso,
            #tool_link: tilt_link,
            #joint_names: [pan, tilt],
        #}
    }
}
