# Setup for full kinematic model

model_config: {
    description: boxbot_description/robots/boxbot_6dof.urdf,
    subsystems: {
        left_arm: {
            name: left_arm,
            base_link: left_arm_base_link,
            tool_link: left_gripper_rail_link,
            joint_names: [left_shoulder_1_joint, left_shoulder_2_joint, left_elbow_joint, left_wrist_1_joint, left_wrist_2_joint, left_wrist_3_joint],
            ik_config: 321,
            DH: [[0.0, 0.0, 0.0, 0.0],
                 [1.57079632679, 0.0, 0.0, -1.24281762533],
                 [0.0, 0.1497, 0.0, -0.32797870146],
                 [1.57079632679, 0.0, 0.1408, 0.0],
                 [1.57079632679, 0.0, 0.0, 0.0],
                 [-1.57079632679, 0.0, 0.1145, -3.14159265358]],
            eef: {
                name: left_arm_gripper,
                type: single_servo_parallel_gripper,
                base_link: left_gripper_rail_link,
                joint_names: [left_gripper_joint],
                limits: [0.002, 0.031],
                speed: 1.57,
                equation: {
                    type: linear,
                    a: -87.964255794,
                    b: 0.174532254,
                }
            }
        },
        right_arm: {
            name: right_arm,
            base_link: right_arm_base_link,
            tool_link: right_gripper_rail_link,
            joint_names: [right_shoulder_1_joint, right_shoulder_2_joint, right_elbow_joint, right_wrist_1_joint, right_wrist_2_joint, right_wrist_3_joint],
            ik_config: 321,
            DH: [[0.0, 0.0, 0.0, 0.0],
                 [1.57079632679, 0.0, 0.0, -1.24281762533],
                 [0.0, 0.1497, 0.0, -0.32797870146],
                 [1.57079632679, 0.0, 0.1408, 0.0],
                 [1.57079632679, 0.0, 0.0, 0.0],
                 [-1.57079632679, 0.0, 0.1145, -3.14159265358]],
            eef: {
                name: right_arm_gripper,
                type: single_servo_parallel_gripper,
                base_link: right_gripper_rail_link,
                joint_names: [right_gripper_joint],
                limits: [0.002, 0.031],
                speed: 1.57,
                equation: {
                    type: linear,
                    a: -87.964255794,
                    b: 0.174532254,
                }
            }
        },
        head: {
            name: head,
            base_link: neck_base_link,
            tool_link: tilt_link,
            joint_names: [pan, tilt],
            eef: {
                name: fake_head_gripper,
                type: none,
                base_link: tilt_link,
            }
        }
    }
}
