# Setup for full kinematic model

model_config: {
    description: boxbot_description/robots/boxbot_6dof.urdf,
    subsystems: {
        left_arm: {
            name: left_arm,
            base_link: left_arm_base_link,
            tool_link: left_gripper_rail_link,
            joint_names: [left_shoulder_1, left_shoulder_2, left_elbow, left_wrist_1, left_wrist_2, left_wrist_3],
            eef: {
                name: left_arm_gripper,
                type: single_servo_parallel_gripper,
                base_link: left_gripper_rail_link,
                joint_names: [left_gripper],
                limits: [0.0, 0.09],
                equation: {
                    type: linear,
                    a: -2.77778,
                    b: 0.0,
                }
            }
        },
        right_arm: {
            name: right_arm,
            base_link: right_arm_base_link,
            tool_link: right_gripper_rail_link,
            joint_names: [right_shoulder_1, right_shoulder_2, right_elbow, right_wrist_1, right_wrist_2, right_wrist_3],
            eef: {
                name: right_arm_gripper,
                type: single_servo_parallel_gripper,
                base_link: right_gripper_rail_link,
                joint_names: [right_gripper],
                limits: [0.0, 0.09],
                equation: {
                    type: linear,
                    a: -2.77778,
                    b: 0.0,
                }
            }
        },
        #head: {
            #name: head,
            #base_link: torso,
            #tool_link: tilt_link,
            #joint_names: [pan, tilt],
        #}
    }
}
